<a href="https://colab.research.google.com/github/ronbalanay/MAT-422/blob/main/MAT422_HW_1_3_Ron_Balanay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.3.1 QR Decomposition

Given a square matrix A with entries in **R**, we can decompose A as A = QR, where Q is an orthogonal matrix and R is an upper triangular matrix. We shall see an example below:



In [4]:
import numpy as np

matrix_string = input("Please enter 4 numbers, separating by commas (i.e. 1,2,3,4): ")
m = np.array([float(x) for x in matrix_string.split(',')])
matrix = np.array([[m[0], m[1]], [m[2], m[3]]])
A = np.array([[m[0], m[1]], [m[2], m[3]]])

print("\nLet A be a 2x2 matrix with entries in R:")
print(matrix)

print("\nWe can use Gram-Schmidt to orthogonalize A, yielding Q.")

a_1 = matrix[:, 0]
a_2 = matrix[:, 1]

print("\nWe'll separate the columns of A as vectors: ")
print("a_1 =", a_1)
print("a_2 =", a_2)

print("\nNow, we'll use a_1 and a_2 to generate an orthonormal set q_1 and q_2, just as we did in chapter 1.2.3.")
print("First, we will normalize a_1 (call this q_1), and subtract the projection of a_2 onto q_1 from a_2 to generate q_2.\n")
#normalize a_1, call this q_1
a_1 /= np.linalg.norm(a_1)
q_1 = a_1

#subtract the projection of a_2 onto q_1 from a_2

a_2 -= a_2.dot(q_1) * q_1

#i had to store the value of a_2 at this point for calculating R later, without using a_2 as a reference variable
w_2 = np.copy(a_2)

a_2 /= np.linalg.norm(a_2)
q_2 = a_2

print("q_1 = ", q_1)
print("q_2 = ", q_2)

# verify that q_1, q_2 are orthogonal and account for floating point rounding error
w_1 = q_1.dot(q_2)
if(np.isclose(w_1,0)):
  w_1 = np.zeros_like(q_1)

Q = np.column_stack((q_1, q_2))

print("\nq_1 ⋅ q_2 =", w_1)
print("\nQ =\n", Q)
print("\nNow, we need to find R. We can calculate R as R = (Q^T)(A) where Q^T is the transpose of Q.")

Q_T = Q.T

print("\nQ^T:\n", Q_T)

R = np.zeros((2,2))
R[0,0] = np.linalg.norm(A[:,0])
R[1,1] = np.linalg.norm(w_2)
R[0,1] = np.dot(Q[:, 0], A[:, 1])

print("\nR =\n", R)

F = Q @ R

print("\nQ * R =\n", F)

print("Now we have decomposed A = QR.")

Please enter 4 numbers, separating by commas (i.e. 1,2,3,4): 9,2,5,3

Let A be a 2x2 matrix with entries in R:
[[9. 2.]
 [5. 3.]]

We can use Gram-Schmidt to orthogonalize A, yielding Q.

We'll separate the columns of A as vectors: 
a_1 = [9. 5.]
a_2 = [2. 3.]

Now, we'll use a_1 and a_2 to generate an orthonormal set q_1 and q_2, just as we did in chapter 1.2.3.
First, we will normalize a_1 (call this q_1), and subtract the projection of a_2 onto q_1 from a_2 to generate q_2.

q_1 =  [0.87415728 0.48564293]
q_2 =  [-0.48564293  0.87415728]

q_1 ⋅ q_2 = [0. 0.]

Q =
 [[ 0.87415728 -0.48564293]
 [ 0.48564293  0.87415728]]

Now, we need to find R. We can calculate R as R = (Q^T)(A) where Q^T is the transpose of Q.

Q^T:
 [[ 0.87415728  0.48564293]
 [-0.48564293  0.87415728]]

R =
 [[10.29563014  3.20524335]
 [ 0.          1.65118597]]

Q * R =
 [[9. 2.]
 [5. 3.]]
Now we have decomposed A = QR.


# 1.3.2 Least-Squares Approximation

Suppose we have a system of equations Ax = b, where A is an m x n matrix, m > n, and b is in R^m. We would like to find an x in R^n such that this equation holds, but in general it is impossible as m > n. Therefore, we would like to find a solution that approximates Ax = b, and this solution should be minimized, i.e. r = b - Ax should be as close to zero as possible.

In fact, we can use QR decomposition to our advantage. Given Ax = b, and A = QR, we have Ax = QRx, and some algebra yields x = (R^-1)b', where R^-1 is the inverse of R and b' = (Q^T)b.



In [5]:
import numpy as np

matrix_string = input("Please enter 6 numbers, separating by commas (i.e. 1,2,3,4,5,6): ")
m = np.array([float(x) for x in matrix_string.split(',')])
A = np.array([[m[0], m[1], m[2]], [m[3], m[4], m[5]]])

print("\nLet A be a 2 x 3 matrix with entries in R:")
print(A)

#compute QR
Q, R = np.linalg.qr(A)

print("\nBy the same method used in section 1.3.1, we decompose A into A = QR, where:\n")
print("Q =\n", Q)
print("R =\n", R)

vector_string = input("\nPlease enter 2 numbers, separating by commas (i.e. 1,2). These will be used for the vector b: ")
b = np.array([float(x) for x in vector_string.split(',')])

print("\nLet b be a vector in R^2:\n", b)

Q_T_b = Q.T @ b

print("\nQ^T * b =\n", Q_T_b)

#Solving R * x = Q^T * b
x, residuals, rank, s = np.linalg.lstsq(R, Q_T_b, rcond=None)

print("\nThe least squares solution x is:\n", x)

w = A @ x
print("\nWe have A * x =\n", w)

residual = A @ x - b

print("\nResidual of the solution:\n", residual)


Please enter 6 numbers, separating by commas (i.e. 1,2,3,4,5,6): 1,5,7,2,3,5

Let A be a 2 x 3 matrix with entries in R:
[[1. 5. 7.]
 [2. 3. 5.]]

By the same method used in section 1.3.1, we decompose A into A = QR, where:

Q =
 [[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
R =
 [[-2.23606798 -4.91934955 -7.60263112]
 [ 0.         -3.13049517 -4.02492236]]

Please enter 2 numbers, separating by commas (i.e. 1,2). These will be used for the vector b: 9,8

Let b be a vector in R^2:
 [9. 8.]

Q^T * b =
 [-11.18033989  -4.47213595]

The least squares solution x is:
 [1.30136986 0.17808219 0.97260274]

We have A * x =
 [9. 8.]

Residual of the solution:
 [-1.77635684e-15  0.00000000e+00]


# 1.3.3 Linear Regression

Linear regression is a technique used to predict the value of unknown data by estimating the relationship between dependent and independent variables. Now, we can apply least-squares approximation to this problem.

Let A be a matrix of input features, where the first column of A is reserved for intercepts. Let β be a vector of coefficients that includes the intercept (β0) and weights of each feature (β1, ... , βn) corresponding to the input feaatures in A. These weights will determine how much each feature influences the predicted outcome. Finally, let y be the vector of target values.

(For example, suppose we are trying to predict house prices based on different input features such as size or location. The target values correspond to the price of each home in a dataset.)

We can use least-squares to approximate the solution, β, to Aβ = y, which we will do below:


In [8]:
import numpy as np

y_string = input("Please enter 3 target values (y), separating by commas (i.e. 1,2,3): ")
y = np.array([float(x) for x in y_string.split(',')])

print("\nLet y be the vector of target values:")
print("y =", y)

feature_1 = input("\nPlease enter the first feature using 3 data points, separating by commas (x11,x21,x31): ")
feature_2 = input("Please enter the second feature using 3 data points, separating by commas (x12,x22,x32): ")

x1 = np.array([float(x) for x in feature_1.split(',')])
x2 = np.array([float(x) for x in feature_2.split(',')])

print("\nWe define our feature matrix X = [x1, x2]:")
print("x1 =", x1)
print("x2 =", x2)

#stack features horizontally

X = np.column_stack((x1, x2))
ones_column = np.ones((3, 1))

#augment X
A = np.hstack((ones_column, X))

print("\nWe augment the feature matrix X with a column of ones to account for the intercept term β0:")
print("A =\n", A)

print("\nNow, we'll use the least squares function to solve for β.")

beta, residuals, rank, s = np.linalg.lstsq(A, y, rcond=None)

#intercept, weights
beta_0 = beta[0]
beta_1, beta_2 = beta[1], beta[2]

print("\nThe least-squares solution β is:\n", beta)
print("\nWhere")
print(f"β0 (intercept) = {beta_0}")
print(f"β1 (weight of feature 1) = {beta_1}")
print(f"β2 (weight of feature 2) = {beta_2}")

y_pred = A @ beta

print("\nOur predicted values are ŷ =\n", y_pred)

print("\nOur residual values are y - ŷ =\n", y - y_pred)

Please enter 3 target values (y), separating by commas (i.e. 1,2,3): 1,2,4

Let y be the vector of target values:
y = [1. 2. 4.]

Please enter the first feature using 3 data points, separating by commas (x11,x21,x31): 8,7,6
Please enter the second feature using 3 data points, separating by commas (x12,x22,x32): 5,9,1

We define our feature matrix X = [x1, x2]:
x1 = [8. 7. 6.]
x2 = [5. 9. 1.]

We augment the feature matrix X with a column of ones to account for the intercept term β0:
A =
 [[1. 8. 5.]
 [1. 7. 9.]
 [1. 6. 1.]]

Now, we'll use the least squares function to solve for β.

The least-squares solution β is:
 [12.08333333 -1.33333333 -0.08333333]

Where
β0 (intercept) = 12.083333333333334
β1 (weight of feature 1) = -1.3333333333333328
β2 (weight of feature 2) = -0.08333333333333359

Our predicted values are ŷ =
 [1. 2. 4.]

Our residual values are y - ŷ =
 [-3.55271368e-15 -1.33226763e-15 -3.55271368e-15]
