<a href="https://colab.research.google.com/github/ronbalanay/MAT-422/blob/main/MAT422_HW_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1.2.1 Linear Spaces

In [ ]:
# generate a linearly independent set in n dimensions


dimensions = int(input("Choose n dimensions (as an integer >= 1): "))

print("\nHere is a set of", dimensions, "vectors:\n")

for i in range(dimensions):
  for j in range(dimensions):
    if(i == j):
      print(1, end = " ")
    else:
      print(0, end = " ")
    print(end = "  ")
  print()

print("\nThese vectors are linearly independent, so they form a vector space of", dimensions, "dimensions. More specifically, this is R^" + str(dimensions) + ".")


Choose n dimensions (as an integer >= 1): 4

Here is a set of 4 vectors:

1   0   0   0   
0   1   0   0   
0   0   1   0   
0   0   0   1   

These vectors are linearly independent, so they form a vector space of 4 dimensions. More specifically, this is R^4.


# 1.2.2 Orthogonality



In [ ]:
import numpy as np

vector_string = input("Enter a vector of any size, separating entries by commas (i.e. 1,0,0): ")

#convert vector to numpy array
vector = np.array([float(x) for x in vector_string.split(',')])

print("\nYour vector is " + str(vector) + ".")
print("\nThe dot product of two vectors is zero iff the vectors are orthogonal.")
print("\nThus, we can find a vector, v, orthogonal to u := " + str(vector) + " by solving u ⋅ v = 0.")

#normalize vector
vector /= np.linalg.norm(vector)
print("\nFirst, we normalize u:\n" + str(vector))

#find orthonormal vector
v = np.random.randn(len(vector))

print("\nNow, we generate a random vector:\n" + str(v))

v -= v.dot(vector) * vector
v /= np.linalg.norm(v)

print("\nFinally, we compute the projection of v onto u and subtract the result from v to find a vector orthogonal to u:\n", v)

w = np.dot(vector, v)

# w is often close but not exactly the zero vector due to floating point limitations, so if w is sufficiently close to the zero vector we set w to the zero vector.
if(np.isclose(w,0)):
  w = np.zeros_like(vector)

print("\nNow we verify that v and u are orthogonal:\n", vector, "⋅", v, "=", w)

Enter a vector of any size, separating entries by commas (i.e. 1,0,0): 1,2,3,0,5

Your vector is [1. 2. 3. 0. 5.].

The dot product of two vectors is zero iff the vectors are orthogonal.

Thus, we can find a vector, v, orthogonal to u := [1. 2. 3. 0. 5.] by solving u ⋅ v = 0.

First, we normalize u:
[0.16012815 0.32025631 0.48038446 0.         0.80064077]

Now, we generate a random vector:
[ 0.52206184  0.45190969 -0.84857999  0.78758407  1.20834235]

Finally, we compute the projection of v onto u and subtract the result from v to find a vector orthogonal to u:
 [ 0.24289602  0.12241548 -0.75298784  0.48325369  0.35424731]

Now we verify that v and u are orthogonal:
 [0.16012815 0.32025631 0.48038446 0.         0.80064077] ⋅ [ 0.24289602  0.12241548 -0.75298784  0.48325369  0.35424731] = [0. 0. 0. 0. 0.]


# 1.2.3 Gram-Schmidt

The technique we used to generate an orthogonal vector in section 1.2.2 above is also known as Gram-Schmidt, and can be used to find a set of orthogonal vectors. In particular, Gram-Schmidt can be used to find an orthonormal basis in certain kinds of vector spaces. We explore this further below.


In [ ]:
import numpy as np

print("Given a single vector with entries in R^3, we will find an orthnormal basis for R^3.\n")
vector_string = input("Enter a vector of size THREE, separating entries by commas (i.e. 1,0,0): ")
vector = np.array([float(x) for x in vector_string.split(',')])

print("\nLet u :=", vector)
#normalize vector
vector /= np.linalg.norm(vector)
print("\nJust as before, we normalize u:\n" + str(vector))

#find orthonormal vector
v = np.random.randn(len(vector))

print("\nThen, we generate a random vector, v, in R^3:\n" + str(v))

# gram-schmidt
v -= v.dot(vector) * vector
v /= np.linalg.norm(v)

print("\nAnd set v = v - proj_u(v) as we did before:\n" + str(v))

w = np.random.randn(len(vector))
print("\nNow, we will use v to find a vector orthogonal to both u and v. We generate a random vector:\n" + str(w))

w -= w.dot(vector) * vector
w -= w.dot(v) * v
w /= np.linalg.norm(w)

print("\nAnd set w = w - proj_u(w) - proj_v(w):\n" + str(w))

print("\nOur orthonormal basis for R^3 is:\n", vector, "\n", v, "\n", w)

print("\nWe shall verify that this set is indeed orthonormal: ")

x_1 = np.dot(vector, v)
x_2 = np.dot(w, vector)
x_3 = np.dot(v, w)

if(np.isclose(x_1,0)):
  x_1 = np.zeros_like(vector)
if(np.isclose(x_2,0)):
  x_2 = np.zeros_like(vector)
if(np.isclose(x_3,0)):
  x_3 = np.zeros_like(vector)


print(vector, "⋅", v, "=", x_1)
print(vector, "⋅", w, "=", x_2)
print(v, "⋅", w, "=", x_3)

Given a single vector with entries in R^3, we will find an orthnormal basis for R^3.

Enter a vector of size THREE, separating entries by commas (i.e. 1,0,0): 1,2,3,4

Let u := [1. 2. 3. 4.]

Just as before, we normalize u:
[0.18257419 0.36514837 0.54772256 0.73029674]

Then, we generate a random vector, v, in R^3:
[-0.64258006  0.47384463  1.02521225  0.60178799]

And set v = v - proj_u(v) as we did before:
[-0.86453182  0.09104096  0.46192915 -0.17583439]

Now, we will use v to find a vector orthogonal to both u and v. We generate a random vector:
[ 0.44490877 -0.0642168   1.036854   -0.57927755]

And set w = w - proj_u(w) - proj_v(w):
[ 0.46198588 -0.1255245   0.67624373 -0.55991702]

Our orthonormal basis for R^3 is:
 [0.18257419 0.36514837 0.54772256 0.73029674] 
 [-0.86453182  0.09104096  0.46192915 -0.17583439] 
 [ 0.46198588 -0.1255245   0.67624373 -0.55991702]

We shall verify that this set is indeed orthonormal: 
[0.18257419 0.36514837 0.54772256 0.73029674] ⋅ [-0.86453182  0

# 1.2.4 Eigenvalues and Eigenvectors

We can think of a matrix as a linear transformation between vector spaces. For example, an m by n matrix, T, with entries in R is a map T: R^n to R^m. If our matrix is square, then we have a linear transformation from a vector space to itself. In general, vectors in our space are transformed to point a different direction with a different magnitude, i.e. T \* u = v. However, there may exist a subset of vectors in our space whose transformation by T yields only a change in magnitude, while leaving the direction fixed, i.e. T \* u = c * u, where c is a scalar. Here, u is an eigenvector, and c is its eigenvalue.

In [ ]:
from numpy import linalg as la

matrix_string = input("Please enter 4 integers, separating by commas (i.e. 1,2,3,4): ")
m = np.array([float(x) for x in matrix_string.split(',')])
matrix = np.array([[m[0], m[1]], [m[2], m[3]]])

print("\nLet M be a 2x2 matrix with entries in R:")
print(matrix)

eigenvalues, eigenvectors = la.eig(matrix)

print("\nEigenvalues e_1, e_2:\n", eigenvalues)

print("\nEigenvectors c_1, c_2:\n", eigenvectors)

e_1 = eigenvectors[:, 0]
e_2 = eigenvectors[:, 1]

x_1 = matrix @ e_1
x_2 = matrix @ e_2

print("\nWe shall verify that these are correct: ")
print("\nM * e_1   = ", x_1)
print("c_1 * e_1 = ", e_1*eigenvalues[0])

print("\nM * e_2   = ", x_2)
print("c_2 * e_2 = ", e_2*eigenvalues[1])

Please enter 4 integers, separating by commas (i.e. 1,2,3,4): 100,20,910,10248

Let M be a 2x2 matrix with entries in R:
[[  100.    20.]
 [  910. 10248.]]

Eigenvalues e_1, e_2:
 [   98.20686001 10249.79313999]

Eigenvectors c_1, c_2:
 [[-0.99600488 -0.00197048]
 [ 0.08929881 -0.99999806]]

We shall verify that these are correct: 

M * e_1   =  [-97.8145119    8.76975566]
c_1 * e_1 =  [-97.8145119    8.76975566]

M * e_2   =  [   -20.19700914 -10249.77324108]
c_2 * e_2 =  [   -20.19700914 -10249.77324108]
